### ISSUE TITLE
`match` is not allowed in a `const fn`

### ISSUE THREAD

**Issue by Blackrucat** [olback/gnome-twitch-2#15]
**WHILE TRYING TO INSTALL  WITH CARGO I HAD THIS ISSUE:**

error[E0658]: `match` is not allowed in a `const fn`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/twitchchat-0.14.8/src/twitch/badge.rs:81:9
   |
81 | /         match self.kind {
82 | |             Admin => "admin",
83 | |             Bits => "bits",
84 | |             Broadcaster => "broadcaster",
...  |
93 | |             Unknown(s) => s,
94 | |         }
   | |_________^
   |
   = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `twitchchat`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `gnome-twitch-2 v0.1.0 (/home/miau/Downloads/gnom e/gnome-twitch-2-master)`, intermediate artifacts can be found at `/home/miau/Downloads/gnom e/gnome-twitch-2-master/target`

Caused by:
  build failed

**Comment by olback** [comment]
This is caused by the `twitchchat` library.

What version of rust are you using?

**Comment by Blackrucat** [comment]
I think it's because I am using rustc, it said that I need to install RustUp, but it will break my system. Maybe I just need a nightly version of RustC not sure.
**rustc --version**
rustc 1.43.0

**Comment by olback** [comment]
It should work if you update rustc to 1.49.0. Match and if statements are now supported in stable.
